"use client";

// components/RootLayout.tsx
import React, { useEffect } from "react";
import "./globals.css";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	useEffect(() => {
		const darkModeMediaQuery = window.matchMedia(
			"(prefers-color-scheme: dark)"
		);
		const classList = document.documentElement.classList;

		const handleChange = (event: MediaQueryListEvent) => {
			if (event.matches) {
				classList.add("dark");
			} else {
				classList.remove("dark");
			}
		};

		if (darkModeMediaQuery.matches) {
			classList.add("dark");
		} else {
			classList.remove("dark");
		}

		darkModeMediaQuery.addEventListener("change", handleChange);

		return () => {
			darkModeMediaQuery.removeEventListener("change", handleChange);
		};
	}, []);

	return (
		<html lang="en">
			<body className="bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
				{children}
			</body>
		</html>
	);
}
